run:
  timeout: 4m
  tests: true
linters:
  enable:
    - asciicheck
    - bodyclose
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - gci
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
